In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


data = load_iris()
X = data.data  
y = data.target 


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


log_reg = LogisticRegression(max_iter=200)  
log_reg.fit(X_train, y_train) 
y_pred_log = log_reg.predict(X_test)  
accuracy_log = accuracy_score(y_test, y_pred_log)  
print("Точность логистической регрессии:", accuracy_log)


knn = KNeighborsClassifier(n_neighbors=3)  
knn.fit(X_train, y_train)  
y_pred_knn = knn.predict(X_test)  
accuracy_knn = accuracy_score(y_test, y_pred_knn)  
print("Точность метода ближайших соседей:", accuracy_knn)


print("\nМатрица ошибок для логистической регрессии:")
print(confusion_matrix(y_test, y_pred_log))
print("\nОтчет классификации для логистической регрессии:")
print(classification_report(y_test, y_pred_log))


print("\nМатрица ошибок для метода ближайших соседей:")
print(confusion_matrix(y_test, y_pred_knn))
print("\nОтчет классификации для метода ближайших соседей:")
print(classification_report(y_test, y_pred_knn))


Точность логистической регрессии: 1.0
Точность метода ближайших соседей: 1.0

Матрица ошибок для логистической регрессии:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Отчет классификации для логистической регрессии:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Матрица ошибок для метода ближайших соседей:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Отчет классификации для метода ближайших соседей:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   m